### ISSUE TITLE
MMM-Pinfo not working on bookworm

### ISSUE THREAD

**Issue by Kayakbabe** [SalekurPolas/MMM-Pinfo#8]
**Describe the bug**
MMM-Pinfo doesn't get or display any data. The labels of the module display , but it just displays "Loading" or 0

**Screenshots**

I did disabled all other modules on my MagicMirror so I know it isn't interference from another third party module. 
I also have a Raspberry Pi 4 based mirror running the up-to-date MM and MMM-Pinfo works on that machine.
So I think it's something with the rpi5. Or maybe the Bookworm version of Debian
I used SDetweil's install scripts to install MM on both the rpi4 and rpi5. Both pi's were virgins, no other stuff on their SD cards except the operating system installed via pi-imager (full desktop OS) and the MM install.

**Desktop (please complete the following information):**
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
Linux mirror 6.1.0-rpi7-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux
MagicMirror [2.26.0] - 01-01-2024

**Comment by KristjanESPERANTO** [comment]
I think it's an issue in the systeminformation package. I've already opened an issue there: <https://github.com/sebhildebrandt/systeminformation/issues/881>

**Comment by ruralguru** [comment]
error occured on pi3 running 64-bit OS.

Static hostname: 
Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.6.31+rpt-rpi-v8
    Architecture: arm64
Revision	: a020d3
Serial		: 00000000f84d5504
Model		: Raspberry Pi 3 Model B Plus Rev 1.3

**Comment by xIExodusIx** [comment]
Habe das gleiche Problem und es müllt die Logs voll.
Pi4 8GB, Debian GNU/Linux 12 (Bücherwurm) 64bit.

**Comment by SalekurPolas** [comment]
@ruralguru, could you please provide more details about the error you encountered on your Raspberry Pi 3 running a 64-bit OS? Specifically, what error message or logs did you receive when the issue occurred?

**Comment by xIExodusIx** [comment]
I have migrated MagicMirror to Raspberry Pi4 in the meantime, unfortunately the MM no longer works after the upgrade to MM 2.29, as soon as it runs again I will get back to you.

**Comment by xIExodusIx** [comment]
Hello, following errors I found in "MagicMirror-error.log"

^[[31m    at /home/pi/MagicMirror/modules/MMM-Pinfo/node_helper.js:169:35^[[39m
^[[31m    at new Promise (<anonymous>)^[[39m
^[[31m    at Class.getCPUInfo (/home/pi/MagicMirror/modules/MMM-Pinfo/node_helper.js:167:16)^[[39m
^[[31m    at Class.collectDynamicInfo (/home/pi/MagicMirror/modules/MMM-Pinfo/node_helper.js:82:20)^[[39m
^[[31m    at async Class.scheduler (/home/pi/MagicMirror/modules/MMM-Pinfo/node_helper.js:69:9)^[[39m
^[[31m(Use `electron --trace-warnings ...` to show where the warning was created)^[[39m
[2024-10-03 10:42:41.967] ^[[31m[ERROR]^[[39m ^[[31m(node:29625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,>
[2024-10-03 10:44:34.064] ^[[33m[WARN] ^[[39m ^[[33mAPI request for 025180526526 failed: Unexpected end of JSON input^[[39m
[2024-10-03 10:46:34.113] ^[[33m[WARN] ^[[39m ^[[33mAPI request for 025180526526 failed: Unexpected end of JSON input^[[39m

**Comment by NatyLang** [comment]
Hi, I might be able to help a bit. Just for info, I run MM on Raspberry Pi 4 model B with Debian 12 (bookworm) as OS. I also encountered the issue where all the stats were stuck in Loading or 0. 

My solution to the problem was to comment out part of the code (below) in node_helper.js around line 168. The issue seems to be that the code references a file that does not exist on my Pi so the variable containing info is undefined. 

`var CPUInfo = this.DeviceInfo[this.DeviceInfo.length - 14].split(":");
var type = CPUInfo[1].slice(1).split(' ');
delete type[type.length-1];
delete type[type.length-2];
delete type[type.length-3];
this.status['CPU'].type = type.toString().replace(new RegExp(',', 'g'), ' ');`

**Be aware** that if you use this solution you won't be able to display CPU type

**Comment by dathbe** [comment]
Not sure if it's related, but I just opened a PR (#14 ) to bump systeminformation to the latest version.  The current version in package.json has a "high" vulnerability that is reported on install, and it also throws a deprecation error in the console log.  The latest version seems to work fine on my system.

**Comment by KristjanESPERANTO** [comment]
@Kayakbabe With the current version of the module I can't reproduce this issue anymore on Debian 12 (bookworm). Can you confirm that?
